---

- name: heartbeat
  freq: 3s
  x: heartbeat
  pubs:
    events:
      name: heartbeat
      description: Publish heartbeat events to heartbeat channel
    errors:
      name: errors
      description: Send error events to errors channel

- name: office-temp
  freq: 15s
  x: temp
  pubs:
    events:
      name: temp
      description: Publish office temperature events to temp channel
    errors:
      name: errors
      description: Send error events to errors channel

